### ISSUE TITLE
New organization

### ISSUE THREAD

**Issue by double-beep** [ThisIsSoorya/mailman.bat#2]
Hello @TheGeekman I have a suggestion, Can you create an organization and import there all the repositories That you have here? I think they are in a mess.
Regards
@double-beep

**Comment by double-beep** [comment]
Also, you can merge all the same language repositories.
Please answer fast,
@double-beep

**Comment by TheGeekman** [comment]
KK.
also make an organization and i may join it

**Comment by double-beep** [comment]
What do you mean with that? Tick what you want.
- [ ] @double-beep will make an organization and @TheGeekman may join.
- [ ] @TheGeekman will make an organization and @double-beep will join.
- [ ] @double-beep will use the existing repositorie (he has one) and will fork all the repositories that @TheGeekman has there. @TheGeekman may join the organization.

Please reopen the issue as not fixed and select what do you want.
@double-beep
